CC=gcc
CFLAGS=-Wall -Wextra -Werror
CLINK=-c
CLIB=-L. -lft
CREZUL=-o ft_display_file

all:
	$(CC) $(CLINK) $(CFLAGS) main.c
	$(CC) main.o $(CLIB) $(CREZUL)
clean:
	rm ft_display_file main.o
fclean: clean 
	
